### ISSUE TITLE
version need to be updated/ add custom version 

### ISSUE THREAD

**Issue by batsyapakasi29** [euphoriys/bedrux#1]
current version is 1.21.44.01,  why not add a version choice list? if its okay for you?

**Comment by theonuverse** [comment]
I added the newest version for the server now. adding choices for versions is possible but the official bedrock server software is constantly updated and I have yet to find a place where it is archived. But if I would find a place, I could add the option to do so.

**Comment by batsyapakasi29** [comment]
ohh i thought you can download old versions just like before... I didn't know they'd removed it
