### ISSUE TITLE
cannot download the bedrockfiles (stuck on HTTP request sent, awaiting response)

### ISSUE THREAD

**Issue by batsyapakasi29** [euphoriys/bedrux#2]
its stuck on HTTP request sent... 
![Screenshot_2024-12-16-09-53-13-51_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/9712411c-d1f6-4755-ae38-26137716f9fb)

**Comment by theonuverse** [comment]
I think this is a wget issue, because downloading the server works fine when using the GUI version on the official Website but wget doesn't work

**Comment by batsyapakasi29** [comment]
can you help me install the files manually?
and where can we continue our conversation? discord?

**Comment by theonuverse** [comment]
sure I can help you, message me on discord: euphoriys

**Comment by batsyapakasi29** [comment]
okay thanks! , confirm my request   discord: MightyCat668
